### ISSUE TITLE
Do you have the working example of this? I tried using this package. I ended up getting Unknown Error: Error: Could not require 'react'. 'react' does not exist in dependencies.

### ISSUE THREAD

**Issue by VineedKaladharan** [Paciolan/remote-component#11]
module.exports = {
  resolve: {
    react: require("react")
  }
};

/**
 * webpack.config.js
 */

module.exports = {
  resolve: {
    alias: {
      "remote-component.config.js": __dirname + "/remote-component.config.js"
    }
  }
};

**Comment by popmanhe** [comment]
Did you include react in your package.json?

**Comment by Jammar** [comment]
@popmanhe Did you make it work in any way?

**Comment by Jammar** [comment]
I finally got it working by ejecting `Create-React-App` and in webpack removing the config of not importing outside of `src/` -> basically just removing this bit:

```javascript
new ModuleScopePlugin(paths.appSrc, [
          paths.appPackageJson,
          reactRefreshOverlayEntry,
        ]),
```

It's _Compiled with warnings_. 

```
./node_modules/@paciolan/remote-component/dist/getDependencies.js
Module not found: Can't resolve 'remote-component.config.js' in 'C:\project-folder\my-remote-repo\node_modules\@paciolan\remote-component\dist'
```

Not sure what to do about that.

I saw [a previous issue](https://github.com/Paciolan/remote-component/issues/3#issuecomment-569345839) regarding this, and how there should be a note about warnings - I couldn't find it.

**Comment by joelnet** [comment]
If you are using CRA, you have to eject and follow the Webpack directions. We're working on better support for CRA, but it's not here yet.

> Module not found: Can't resolve 'remote-component.config.js' 

You should not get this error. It sounds like a problem with the webpack alias or the `remote-component.config.js` file is missing. 

If you could post the source for your project I can help out.

We will have better examples up in the near future.

**Comment by Jammar** [comment]
> If you are using CRA, you have to eject and follow the Webpack directions. We're working on better support for CRA, but it's not here yet.

I've ejected and followed the Webpack directions :) the only thing I've done differently (that I know of) is, in `webpack.config.js`, remove following:

```javascript
new ModuleScopePlugin(paths.appSrc, [
          paths.appPackageJson,
          reactRefreshOverlayEntry,
        ])
```

Otherwise I couldn't import `remote-component.config.js` which was outside `src`. 

> > Module not found: Can't resolve 'remote-component.config.js'
> You should not get this error. It sounds like a problem with the webpack alias or the `remote-component.config.js` file is missing.
> If you could post the source for your project I can help out.

Cheers, thanks a lot, and for answering [my other question](https://github.com/Paciolan/remote-component/issues/15). Great project.

It seems to be working fine but I get the warning:

> Compiled with warnings.
>./node_modules/@paciolan/remote-component/dist/getDependencies.js
Module not found: Can't resolve 'remote-component.config.js' in 'C:\Projekt\grid-and-remote\node_modules\@paciolan\remote-component\dist'

**Here's the source code**

```javascript
/*
 * ./src/components/RemoteComponent.js
 */

import {
  createRemoteComponent,
  createRequires
} from "@paciolan/remote-component";
import { resolve } from "../../remote-component.config.js";

const requires = createRequires(resolve);
export const RemoteComponent = createRemoteComponent({ requires });
```

```javascript
/* 
 * ./remote-component.config.js
 *
 * Dependencies for Remote Components
 */

module.exports = {
  resolve: {
    react: require("react"),
    "styled-components": require("styled-components")
  }
};
```

```javascript
/*
* ./config/webpack.config.js
*/  
... 
    resolve: {
      modules: ['node_modules', paths.appNodeModules].concat(
        modules.additionalModulePaths || []
      ),
      extensions: paths.moduleFileExtensions
        .map(ext => `.${ext}`)
        .filter(ext => useTypeScript || !ext.includes('ts')),
      alias: {
        "remote-component.config.js": __dirname + "/remote-component.config.js",
        'react-native': 'react-native-web',
... etc ...
```

🍻

**Comment by joelnet** [comment]
Oh that's great! CRA does some magical things, so the directions are going to be slightly different for CRA. I have tested CRA a bit and it seemed like it would take more than just a quick fix. It is our plan to support CRA and hopefully soon. But until then it's going to be a PITA to get it working.

Also the directions for creating a remote component and consuming a remote component will be different. Which one was this? were you trying to consume a remote component with this project?

**Comment by Jammar** [comment]
> Oh that's great! CRA does some magical things, so the directions are going to be slightly different for CRA. I have tested CRA a bit and it seemed like it would take more than just a quick fix.

Oh so you've been setting up it from scratch, not through CRA?

> Also the directions for creating a remote component and consuming a remote component will be different. Which one was this? were you trying to consume a remote component with this project?

This was the consumer. I'm looking at creating remote components too.

**Comment by joelnet** [comment]
I have updated the docs for CRA here. It looks like you can use CRA fine without the need to eject.

https://github.com/Paciolan/remote-component#create-react-app-cra

Cheers 🍻

**Comment by hotpothot** [comment]
Thanks @joelnet for update the doc https://github.com/Paciolan/remote-component#create-react-app-cra. However, I feel what you added, it doesn't solve my problem. Since I didn't have issue by using CRA on the client who consume the RemoteComponent.  The problem I had is on the other side which how to make my own remote component work instead of consuming HelloWorld.js created by you.

**Comment by joelnet** [comment]
> The problem I had is on the other side which how to make my own remote component work instead of consuming HelloWorld.js created by you.


I'll have more examples up shortly!

**Comment by joelnet** [comment]
> The problem I had is on the other side which how to make my own remote component work instead of consuming HelloWorld.js created by you.

Have you tried this https://github.com/Paciolan/remote-component-starter?

**Comment by hotpothot** [comment]
Thanks @joelnet. I tried https://github.com/Paciolan/remote-component-starter.
The error I hit is 
Unknown Error: Error: Could not require 'styled-components'. 'styled-components' does not exist in dependencies.
I feel it is the same issue I hit earlier. Basically the external package can't be loaded properly.

I noticed in your example webpack bundled HelloWorld.js returns module as an **array** (index 0 : react, index1: helloworld component), while in remote-component-starter or myself made components the webpack bundled are return as **object** instead of array. It seems the dependances are not loaded in the expected sequence when the webpack bundled are return as **object** 

Do you know how can I generate webpack bundle module in array instead of object?

**HelloWorld.js: modules returned as array.** 
([
/* 0 */
/***/ (function(module, exports) {

module.exports = require("react");

/***/ }),
/* 1 */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(0);
/* harmony import */ var react__WEBPACK_IMPORTED_MODULE_0___default = /*#__PURE__*/__webpack_require__.n(react__WEBPACK_IMPORTED_MODULE_0__);
/**
 * Entrypoint of the Remote Component.
 */

var RemoteComponent = function RemoteComponent(_ref) {
  var name = _ref.name;
  return react__WEBPACK_IMPORTED_MODULE_0___default.a.createElement("div", null, "Hello ", name, "!");
};

RemoteComponent.defaultProps = {
  name: "World"
};
/* harmony default export */ __webpack_exports__["default"] = (RemoteComponent);

/***/ })
/******/ ])));


remote-component-start bundled main.js return modules as object
({
/***/ "./node_modules/@babel/runtime/helpers/arrayLikeToArray.js":
/*!*****************************************************************!*\
  !*** ./node_modules/@babel/runtime/helpers/arrayLikeToArray.js ***!
  \*****************************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

eval("function _arrayLikeToArray(arr, len) {\n  if (len == null || len > arr.length) len = arr.length;\n\n  for (var i = 0, arr2 = new Array(len); i < len; i++) {\n    arr2[i] = arr[i];\n  }\n\n  return arr2;\n}\n\nmodule.exports = _arrayLikeToArray;\n\n//# sourceURL=webpack:///./node_modules/@babel/runtime/helpers/arrayLikeToArray.js?");

/***/ }),...}

**Comment by joelnet** [comment]
> Unknown Error: Error: Could not require 'styled-components'. 'styled-components' does not exist in dependencies.

This typically happens when the Remote Component has an external dependency that the React App does not supply.

I'm not sure why `styled-components` is part of this. This must have been some internal dependency that snuck into this project.

**Comment by joelnet** [comment]
I have made some updates to https://github.com/Paciolan/remote-component-starter. Please pull the latest version and try again.

I have removed some unnecessary dependencies and help simplify the project.

**Comment by joelnet** [comment]
I just made a major update to the README. This includes some docs for CRA and Next.js. I hope this helps clear up some of the issues surrounding the Remote Component setup.

Cheers 🍻
